"""Autonomous monitoring agent — proactive health surveillance.

Runs as a background ``asyncio.Task`` that periodically inspects
pipeline health using the agent's own tool set.  When it detects
problems it:

  * Attempts automatic remediation (e.g., reset circuit breaker,
    flush stale queue entries, auto-tune confidence).
  * Broadcasts alert events via the WebSocket channel so operators
    and the Streamlit visualiser are notified in real time.
  * Records observations in the KnowledgeBase for trend analysis.

The monitor is intentionally *conservative* — it only takes action
when clear thresholds are breached, and logs everything it does.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class HealthAlert:
    """A single health alert generated by the monitor."""

    severity: AlertSeverity
    source: str  # e.g., "circuit_breaker", "queue_pressure"
    message: str
    details: dict[str, Any] = field(default_factory=dict)
    auto_remediated: bool = False
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "agent_health_alert",
            "severity": self.severity.value,
            "source": self.source,
            "message": self.message,
            "details": self.details,
            "auto_remediated": self.auto_remediated,
            "timestamp": self.timestamp,
        }


class AutonomousMonitor:
    """Background health monitor that periodically checks and heals the pipeline.

    Parameters
    ----------
    registry:
        ToolRegistry for invoking diagnostic/control tools.
    context:
        ToolExecutionContext with live component references.
    interval_seconds:
        Seconds between health checks (default 60).
    broadcast_fn:
        Async callable for sending WebSocket alerts.  When *None*,
        alerts are only logged.
    """

    def __init__(
        self,
        registry: Any,
        context: Any,
        *,
        interval_seconds: float = 60.0,
        broadcast_fn: Any = None,
    ) -> None:
        self._registry = registry
        self._context = context
        self._interval = interval_seconds
        self._broadcast = broadcast_fn

        self._task: asyncio.Task[None] | None = None
        self._running = False
        self._alerts: list[HealthAlert] = []
        self._check_count = 0
        self._last_check: float = 0.0

    # ── Lifecycle ─────────────────────────────────────────────────

    async def start(self) -> None:
        """Start the background monitoring loop."""
        if self._running:
            return
        self._running = True
        self._task = asyncio.create_task(self._loop(), name="agent_monitor")
        logger.info("autonomous_monitor_started interval=%.0fs", self._interval)

    async def stop(self) -> None:
        """Gracefully stop the monitoring loop."""
        self._running = False
        if self._task and not self._task.done():
            self._task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await self._task
        logger.info("autonomous_monitor_stopped checks=%d", self._check_count)

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def recent_alerts(self) -> list[dict[str, Any]]:
        """Return the last 50 alerts as dicts."""
        return [a.to_dict() for a in self._alerts[-50:]]

    def get_stats(self) -> dict[str, Any]:
        return {
            "running": self._running,
            "check_count": self._check_count,
            "last_check": self._last_check,
            "alert_count": len(self._alerts),
            "interval_seconds": self._interval,
        }

    # ── Background loop ──────────────────────────────────────────

    async def _loop(self) -> None:
        """Main monitoring loop — runs until stopped."""
        # Wait a short warm-up period before the first check
        await asyncio.sleep(min(self._interval, 10.0))

        while self._running:
            try:
                await self._run_health_check()
            except asyncio.CancelledError:
                break
            except Exception:
                logger.exception("monitor_check_failed")

            try:
                await asyncio.sleep(self._interval)
            except asyncio.CancelledError:
                break

    async def _run_health_check(self) -> None:
        """Execute one full health check cycle."""
        self._check_count += 1
        self._last_check = time.time()

        alerts: list[HealthAlert] = []

        # 1. Check system health
        alerts.extend(await self._check_system_health())

        # 2. Check queue pressure
        alerts.extend(await self._check_queue_pressure())

        # 3. Check OCR strategy health
        alerts.extend(await self._check_ocr_health())

        # Broadcast any alerts
        for alert in alerts:
            self._alerts.append(alert)
            logger.log(
                logging.WARNING if alert.severity != AlertSeverity.INFO else logging.INFO,
                "health_alert severity=%s source=%s msg=%s remediated=%s",
                alert.severity.value,
                alert.source,
                alert.message,
                alert.auto_remediated,
            )
            if self._broadcast:
                try:
                    await self._broadcast(json.dumps(alert.to_dict()))
                except Exception:
                    logger.debug("alert_broadcast_failed", exc_info=True)

        # Trim alert history
        if len(self._alerts) > 500:
            self._alerts = self._alerts[-250:]

    # ── Individual health checks ─────────────────────────────────

    async def _check_system_health(self) -> list[HealthAlert]:
        """Check pipeline and VRAM health."""
        alerts: list[HealthAlert] = []

        result = await self._registry.invoke(
            "get_system_health",
            {},
            context=self._context,
        )
        if not result.success:
            return alerts

        data = result.data or {}

        # Check VRAM usage
        vram = data.get("vram", {})
        used_pct = vram.get("used_percent", 0)
        if used_pct > 90:
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.CRITICAL,
                    source="vram",
                    message=f"VRAM usage critical: {used_pct:.1f}%",
                    details=vram,
                )
            )
        elif used_pct > 75:
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.WARNING,
                    source="vram",
                    message=f"VRAM usage high: {used_pct:.1f}%",
                    details=vram,
                )
            )

        # Check pipeline state
        pipeline_state = data.get("pipeline_state", "unknown")
        if pipeline_state not in ("running", "unknown"):
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.CRITICAL,
                    source="pipeline",
                    message=f"Pipeline state: {pipeline_state}",
                    details={"state": pipeline_state},
                )
            )

        # Check circuit breaker
        cb_state = data.get("circuit_breaker_state", "closed")
        if cb_state == "open":
            # Attempt auto-remediation
            heal_result = await self._registry.invoke(
                "self_heal_pipeline",
                {},
                context=self._context,
            )
            remediated = heal_result.success and (heal_result.data or {}).get("actions_taken", [])
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.WARNING,
                    source="circuit_breaker",
                    message="Circuit breaker is OPEN — LLM OCR unavailable",
                    details={"cb_state": cb_state, "heal_result": str(heal_result.data)[:200]},
                    auto_remediated=bool(remediated),
                )
            )

        return alerts

    async def _check_queue_pressure(self) -> list[HealthAlert]:
        """Check inference queue for backpressure."""
        alerts: list[HealthAlert] = []

        result = await self._registry.invoke(
            "get_queue_pressure",
            {},
            context=self._context,
        )
        if not result.success:
            return alerts

        data = result.data or {}
        depth = data.get("current_depth", 0)
        maxsize = data.get("maxsize", 100)
        fill_pct = (depth / maxsize * 100) if maxsize > 0 else 0

        if fill_pct > 80:
            # Attempt to flush stale entries
            flush_result = await self._registry.invoke(
                "flush_inference_queue",
                {},
                context=self._context,
            )
            flushed = (flush_result.data or {}).get("flushed", 0) if flush_result.success else 0
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.WARNING,
                    source="queue_pressure",
                    message=f"Queue fill at {fill_pct:.0f}% ({depth}/{maxsize})",
                    details={"depth": depth, "maxsize": maxsize, "flushed": flushed},
                    auto_remediated=flushed > 0,
                )
            )
        elif fill_pct > 50:
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.INFO,
                    source="queue_pressure",
                    message=f"Queue fill at {fill_pct:.0f}%",
                    details={"depth": depth, "maxsize": maxsize},
                )
            )

        return alerts

    async def _check_ocr_health(self) -> list[HealthAlert]:
        """Check OCR strategy balance and error rates."""
        alerts: list[HealthAlert] = []

        result = await self._registry.invoke(
            "get_ocr_strategy_stats",
            {},
            context=self._context,
        )
        if not result.success:
            return alerts

        data = result.data or {}
        primary = data.get("primary_success_rate", 1.0)
        fallback_pct = data.get("fallback_usage_percent", 0)

        if primary < 0.5:
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.WARNING,
                    source="ocr_primary",
                    message=f"Primary OCR success rate low: {primary:.1%}",
                    details=data,
                )
            )

        if fallback_pct > 40:
            alerts.append(
                HealthAlert(
                    severity=AlertSeverity.WARNING,
                    source="ocr_fallback",
                    message=f"Fallback OCR usage high: {fallback_pct:.0f}%",
                    details=data,
                )
            )

        return alerts
