"""Data models for the Manager Agent subsystem.

Defines the structured data types used throughout the manager for
context analysis, pipeline composition, component resolution, and
conflict detection.  All models are frozen dataclasses for immutability.
"""

from __future__ import annotations

import enum
import time
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from uni_vision.components.base import (
        ComponentCapability,
    )

# ── Context analysis ──────────────────────────────────────────────


class SceneType(str, enum.Enum):
    """High-level scene classification derived from frame analysis."""

    TRAFFIC = "traffic"
    PARKING = "parking"
    SURVEILLANCE = "surveillance"
    INDUSTRIAL = "industrial"
    INDOOR = "indoor"
    GENERAL = "general"
    UNKNOWN = "unknown"


class TaskPriority(str, enum.Enum):
    CRITICAL = "critical"
    HIGH = "high"
    NORMAL = "normal"
    LOW = "low"


@dataclass(frozen=True)
class DiscoveryQuery:
    """An LLM-generated search query for open-ended component discovery.

    The Manager Agent (Gemma 4 E2B) produces these when it determines that
    the current frame requires capabilities beyond the known enum set.
    Each query targets a specific source (HuggingFace, PyPI, GitHub)
    with free-form search terms and contextual rationale.
    """

    query: str  # Free-form search string
    source: str = "all"  # huggingface | pypi | github | all
    capability_hint: str = ""  # What capability this addresses
    context_rationale: str = ""  # Why this search is needed
    vram_budget_mb: int = 0  # Max VRAM for candidates
    priority: int = 0  # Higher = more important


@dataclass(frozen=True)
class FrameContext:
    """Result of the Context Analyzer — tells the Manager Agent what
    capabilities are needed for this frame / stream context.

    Attributes
    ----------
    scene_type:
        Broad scene classification.
    required_capabilities:
        Capabilities that MUST be present in the composed pipeline
        (well-known enum-based).
    optional_capabilities:
        Nice-to-have capabilities if VRAM budget permits (well-known).
    dynamic_required:
        Free-form capability strings generated by the LLM that go beyond
        the fixed ComponentCapability enum.  These represent open-ended
        needs that the LLM has identified through reasoning.
    dynamic_optional:
        Free-form optional capabilities from LLM reasoning.
    discovery_queries:
        LLM-generated search queries for open internet component
        discovery.  These drive unbounded search across HuggingFace,
        PyPI, and GitHub.
    detected_objects_hint:
        Free-text hints from a lightweight pre-scan (e.g., "vehicles
        detected", "person visible").
    priority:
        Processing urgency — affects component loading order.
    camera_id:
        Source camera identifier for provenance.
    metadata:
        Additional context hints (lighting, weather, etc.).
    """

    scene_type: SceneType = SceneType.UNKNOWN
    required_capabilities: frozenset[ComponentCapability] = frozenset()
    optional_capabilities: frozenset[ComponentCapability] = frozenset()
    dynamic_required: frozenset[str] = frozenset()
    dynamic_optional: frozenset[str] = frozenset()
    discovery_queries: list[DiscoveryQuery] = field(default_factory=list)
    detected_objects_hint: str = ""
    priority: TaskPriority = TaskPriority.NORMAL
    camera_id: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def all_required_labels(self) -> frozenset[str]:
        """Union of enum-based and dynamic required capability labels."""
        return frozenset({c.value for c in self.required_capabilities} | self.dynamic_required)

    @property
    def all_optional_labels(self) -> frozenset[str]:
        """Union of enum-based and dynamic optional capability labels."""
        return frozenset({c.value for c in self.optional_capabilities} | self.dynamic_optional)


# ── Pipeline composition ──────────────────────────────────────────


@dataclass(frozen=True)
class StageSpec:
    """A single stage in a composed pipeline.

    Each stage specifies which component capability is required and
    what component (if already resolved) will fulfil it.

    For standard (enum) capabilities, ``required_capability`` is set.
    For dynamically discovered capabilities (free-form strings from the
    LLM), ``required_capability`` is ``None`` and ``dynamic_capability``
    holds the free-form label.
    """

    stage_name: str
    required_capability: ComponentCapability | None = None
    dynamic_capability: str | None = None  # free-form LLM-discovered
    component_id: str | None = None  # If resolved
    is_optional: bool = False
    input_key: str = "image"
    output_key: str = "image"
    config_overrides: dict[str, Any] = field(default_factory=dict)

    @property
    def capability_label(self) -> str:
        """Human-readable capability name for logging / display."""
        if self.required_capability is not None:
            return self.required_capability.value
        return self.dynamic_capability or "unknown"


@dataclass(frozen=True)
class PipelineBlueprint:
    """A fully-specified dynamic pipeline ready for execution.

    Created by the PipelineComposer based on Manager Agent decisions.
    """

    blueprint_id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    name: str = ""
    context: FrameContext | None = None
    stages: list[StageSpec] = field(default_factory=list)
    estimated_vram_mb: int = 0
    estimated_latency_ms: float = 0.0
    created_at: float = field(default_factory=time.time)

    @property
    def required_component_ids(self) -> set[str]:
        return {s.component_id for s in self.stages if s.component_id}


# ── Component resolution ─────────────────────────────────────────


class ResolutionStatus(str, enum.Enum):
    PENDING = "pending"
    SEARCHING = "searching"
    FOUND = "found"
    DOWNLOADING = "downloading"
    INSTALLED = "installed"
    FAILED = "failed"
    CONFLICT = "conflict"


@dataclass
class ComponentCandidate:
    """A candidate component discovered during resolution.

    May come from the local registry, HuggingFace Hub, or PyPI.
    """

    component_id: str
    name: str
    source: str  # builtin | huggingface | pypi | github
    source_id: str  # e.g., "huggingface:keremberke/yolov8n-plate-detection"
    capabilities: set[ComponentCapability] = field(default_factory=set)
    vram_mb: int = 0
    score: float = 0.0  # Relevance score (0.0–1.0)
    python_requirements: list[str] = field(default_factory=list)
    model_class: str = ""  # For HuggingFace models
    metadata: dict[str, Any] = field(default_factory=dict)
    trusted: bool = False

    @property
    def is_local(self) -> bool:
        return self.source == "builtin"


@dataclass
class ResolutionResult:
    """Outcome of resolving a capability requirement."""

    capability: ComponentCapability
    status: ResolutionStatus = ResolutionStatus.PENDING
    selected_candidate: ComponentCandidate | None = None
    all_candidates: list[ComponentCandidate] = field(default_factory=list)
    error: str = ""


# ── Conflict detection ────────────────────────────────────────────


class ConflictType(str, enum.Enum):
    VRAM_EXCEEDED = "vram_exceeded"
    DEPENDENCY_CLASH = "dependency_clash"  # Incompatible pip packages
    DEVICE_MISMATCH = "device_mismatch"  # GPU required but unavailable
    CAPABILITY_OVERLAP = "capability_overlap"  # Two components for same slot
    VERSION_CONFLICT = "version_conflict"  # Different versions of same lib
    LICENSE_INCOMPATIBLE = "license_incompatible"


@dataclass
class ComponentConflict:
    """A detected conflict between components or resources."""

    conflict_type: ConflictType
    component_ids: list[str]
    description: str
    severity: TaskPriority = TaskPriority.HIGH
    suggested_resolution: str = ""
    auto_resolvable: bool = False


@dataclass
class ConflictReport:
    """Full conflict analysis for a proposed component set."""

    conflicts: list[ComponentConflict] = field(default_factory=list)
    total_vram_required_mb: int = 0
    vram_available_mb: int = 0
    is_feasible: bool = True

    @property
    def has_conflicts(self) -> bool:
        return len(self.conflicts) > 0

    @property
    def blocking_conflicts(self) -> list[ComponentConflict]:
        return [c for c in self.conflicts if c.severity in (TaskPriority.CRITICAL, TaskPriority.HIGH)]


# ── Manager Agent decision ────────────────────────────────────────


class ManagerDecision(str, enum.Enum):
    """What the Manager Agent decided to do after reasoning."""

    USE_EXISTING = "use_existing"  # Current pipeline works
    SWAP_COMPONENTS = "swap_components"  # Replace some components
    BUILD_NEW_PIPELINE = "build_new_pipeline"
    DOWNLOAD_AND_INTEGRATE = "download_and_integrate"
    OFFLOAD_FOR_VRAM = "offload_for_vram"
    REPORT_INFEASIBLE = "report_infeasible"


@dataclass
class ManagerAction:
    """A concrete action the Manager Agent wants to take."""

    decision: ManagerDecision
    target_blueprint: PipelineBlueprint | None = None
    components_to_load: list[str] = field(default_factory=list)
    components_to_unload: list[str] = field(default_factory=list)
    components_to_download: list[ComponentCandidate] = field(default_factory=list)
    conflict_resolutions: list[str] = field(default_factory=list)
    reasoning: str = ""


# ── Pipeline execution result ─────────────────────────────────────


@dataclass
class StageResult:
    """Output of a single pipeline stage execution."""

    stage_name: str
    component_id: str
    output: Any = None
    elapsed_ms: float = 0.0
    success: bool = True
    error: str = ""


@dataclass
class PipelineExecutionResult:
    """Aggregated result of a full dynamic pipeline run."""

    blueprint_id: str
    stage_results: list[StageResult] = field(default_factory=list)
    final_output: Any = None
    total_elapsed_ms: float = 0.0
    success: bool = True
    error: str = ""

    @property
    def failed_stages(self) -> list[StageResult]:
        return [s for s in self.stage_results if not s.success]
